export const currencyOptions = [
  { label: 'Afghan afghani (؋)', value: 'afn' },
  { label: 'Albanian lek (L)', value: 'all' },
  { label: 'Algerian dinar (دج)', value: 'dzd' },
  { label: 'Angolan kwanza (Kz)', value: 'aoa' },
  { label: 'Argentine peso ($)', value: 'ars' },
  { label: 'Armenian dram (֏)', value: 'amd' },
  { label: 'Aruban florin (ƒ)', value: 'awg' },
  { label: 'Australian dollar ($)', value: 'aud' },
  { label: 'Azerbaijani manat (₼)', value: 'azn' },
  { label: 'Bahamian dollar ($)', value: 'bsd' },
  { label: 'Bangladeshi taka (৳)', value: 'bdt' },
  { label: 'Barbadian dollar (Bds$)', value: 'bbd' },
  { label: 'Belize dollar (BZ$)', value: 'bzd' },
  { label: 'Bermudian dollar ($)', value: 'bmd' },
  { label: 'Bolivian boliviano (Bs.)', value: 'bob' },
  { label: 'Bosnia & Herzegovina convertible mark (KM)', value: 'bam' },
  { label: 'Botswana pula (P)', value: 'bwp' },
  { label: 'Brazilian real (R$)', value: 'brl' },
  { label: 'British pound (£)', value: 'gbp' },
  { label: 'Brunei dollar ($)', value: 'bnd' },
  { label: 'Bulgarian lev (лв)', value: 'bgn' },
  { label: 'Burundian franc (FBu)', value: 'bif' },
  { label: 'Cambodian riel (៛)', value: 'khr' },
  { label: 'Canadian dollar ($)', value: 'cad' },
  { label: 'Cape Verdean escudo (Esc)', value: 'cve' },
  { label: 'Cayman Islands dollar ($)', value: 'kyd' },
  { label: 'Central African CFA franc (FCFA)', value: 'xaf' },
  { label: 'CFP franc (₣)', value: 'xpf' },
  { label: 'Chilean peso ($)', value: 'clp' },
  { label: 'Chinese renminbi yuan (¥)', value: 'cny' },
  { label: 'Colombian peso ($)', value: 'cop' },
  { label: 'Comorian franc (CF)', value: 'kmf' },
  { label: 'Congolese franc (FC)', value: 'cdf' },
  { label: 'Costa Rican colón (₡)', value: 'crc' },
  { label: 'Croatian kuna (kn)', value: 'hrk' },
  { label: 'Czech koruna (Kč)', value: 'czk' },
  { label: 'Danish krone (kr)', value: 'dkk' },
  { label: 'Djiboutian franc (Fdj)', value: 'djf' },
  { label: 'Dominican peso (RD$)', value: 'dop' },
  { label: 'East Caribbean dollar ($)', value: 'xcd' },
  { label: 'Egyptian pound (£)', value: 'egp' },
  { label: 'Ethiopian birr (Br)', value: 'etb' },
  { label: 'Euro (€)', value: 'eur' },
  { label: 'Falkland Islands pound (£)', value: 'fkp' },
  { label: 'Fijian dollar ($)', value: 'fjd' },
  { label: 'Gambian dalasi (D)', value: 'gmd' },
  { label: 'Georgian lari (₾)', value: 'gel' },
  { label: 'Gibraltar pound (£)', value: 'gip' },
  { label: 'Guatemalan quetzal (Q)', value: 'gtq' },
  { label: 'Guinean franc (FG)', value: 'gnf' },
  { label: 'Guyanese dollar ($)', value: 'gyd' },
  { label: 'Haitian gourde (G)', value: 'htg' },
  { label: 'Honduran lempira (L)', value: 'hnl' },
  { label: 'Hong Kong dollar ($)', value: 'hkd' },
  { label: 'Hungarian forint (Ft)', value: 'huf' },
  { label: 'Icelandic króna (kr)', value: 'isk' },
  { label: 'Indian rupee (₹)', value: 'inr' },
  { label: 'Indonesian rupiah (Rp)', value: 'idr' },
  { label: 'Israeli new sheqel (₪)', value: 'ils' },
  { label: 'Jamaican dollar (J$)', value: 'jmd' },
  { label: 'Japanese yen (¥)', value: 'jpy' },
  { label: 'Kazakhstani tenge (₸)', value: 'kzt' },
  { label: 'Kenyan shilling (KSh)', value: 'kes' },
  { label: 'Kyrgyzstani som (som)', value: 'kgs' },
  { label: 'Lao kip (₭)', value: 'lak' },
  { label: 'Lebanese pound (£)', value: 'lbp' },
  { label: 'Lesotho loti (L)', value: 'lsl' },
  { label: 'Liberian dollar ($)', value: 'lrd' },
  { label: 'Macanese pataca (MOP$)', value: 'mop' },
  { label: 'Macedonian denar (ден)', value: 'mkd' },
  { label: 'Malagasy ariary (Ar)', value: 'mga' },
  { label: 'Malawian kwacha (MK)', value: 'mwk' },
  { label: 'Malaysian ringgit (RM)', value: 'myr' },
  { label: 'Maldivian rufiyaa (ރ)', value: 'mvr' },
  { label: 'Mauritanian ouguiya (UM)', value: 'mro' },
  { label: 'Mauritian rupee (Rs)', value: 'mur' },
  { label: 'Mexican peso ($)', value: 'mxn' },
  { label: 'Moldovan leu (L)', value: 'mdl' },
  { label: 'Mongolian tögrög (₮)', value: 'mnt' },
  { label: 'Moroccan dirham (د.م.)', value: 'mad' },
  { label: 'Mozambican metical (MT)', value: 'mzn' },
  { label: 'Myanmar kyat (K)', value: 'mmk' },
  { label: 'Namibian dollar ($)', value: 'nad' },
  { label: 'Nepalese rupee (रू)', value: 'npr' },
  { label: 'Netherlands Antillean gulden (ƒ)', value: 'ang' },
  { label: 'New Taiwan dollar (NT$)', value: 'twd' },
  { label: 'New Zealand dollar ($)', value: 'nzd' },
  { label: 'Nicaraguan córdoba (C$)', value: 'nio' },
  { label: 'Nigerian naira (₦)', value: 'ngn' },
  { label: 'Norwegian krone (kr)', value: 'nok' },
  { label: 'Pakistani rupee (₨)', value: 'pkr' },
  { label: 'Panamanian balboa (B/.)', value: 'pab' },
  { label: 'Papua New Guinean kina (K)', value: 'pgk' },
  { label: 'Paraguayan guaraní (₲)', value: 'pyg' },
  { label: 'Peruvian nuevo sol (S/.)', value: 'pen' },
  { label: 'Philippine peso (₱)', value: 'php' },
  { label: 'Polish złoty (zł)', value: 'pln' },
  { label: 'Qatari riyal (ر.ق)', value: 'qar' },
  { label: 'Romanian leu (L)', value: 'ron' },
  { label: 'Russian ruble (₽)', value: 'rub' },
  { label: 'Rwandan franc (RWF)', value: 'rwf' },
  { label: 'São Tomé and Príncipe dobra (Db)', value: 'std' },
  { label: 'Saint Helenian pound (£)', value: 'shp' },
  { label: 'Salvadoran colón (₡)', value: 'svc' },
  { label: 'Samoan tala (WST)', value: 'wst' },
  { label: 'Saudi riyal (ر.س)', value: 'sar' },
  { label: 'Serbian dinar (дин.)', value: 'rsd' },
  { label: 'Seychellois rupee (Rs)', value: 'scr' },
  { label: 'Sierra Leonean leone (SLL)', value: 'sll' },
  { label: 'Singapore dollar ($)', value: 'sgd' },
  { label: 'Solomon Islands dollar ($)', value: 'sbd' },
  { label: 'Somali shilling (SOS)', value: 'sos' },
  { label: 'South African rand (R)', value: 'zar' },
  { label: 'South Korean won (₩)', value: 'krw' },
  { label: 'Sri Lankan rupee (රු)', value: 'lkr' },
  { label: 'Surinamese dollar (SRD)', value: 'srd' },
  { label: 'Swazi lilangeni (E)', value: 'szl' },
  { label: 'Swedish krona (kr)', value: 'sek' },
  { label: 'Swiss franc (CHF)', value: 'chf' },
  { label: 'Tajikistani somoni (ЅМ)', value: 'tjs' },
  { label: 'Tanzanian shilling (TSh)', value: 'tzs' },
  { label: 'Thai baht (฿)', value: 'thb' },
  { label: 'Tongan paʻanga (T$)', value: 'top' },
  { label: 'Trinidad and Tobago dollar (TT$)', value: 'ttd' },
  { label: 'Turkish lira (₺)', value: 'try' },
  { label: 'Ugandan shilling (UGX)', value: 'ugx' },
  { label: 'Ukrainian hryvnia (₴)', value: 'uah' },
  { label: 'United Arab Emirates dirham (د.إ)', value: 'aed' },
  { label: 'United States dollar ($)', value: 'usd' },
  { label: 'Uruguayan peso ($U)', value: 'uyu' },
  { label: 'Uzbekistani som (soʻm)', value: 'uzs' },
  { label: 'Vanuatu vatu (VT)', value: 'vuv' },
  { label: 'Vietnamese đồng (₫)', value: 'vnd' },
  { label: 'West African CFA franc (CFA)', value: 'xof' },
  { label: 'Yemeni rial (﷼)', value: 'yer' },
  { label: 'Zambian kwacha (ZMW)', value: 'zmw' },
];

export const languageArray = [
  { label: "Abkhazian", value: "ab" },
  { label: "Afar", value: "aa" },
  { label: "Afrikaans", value: "af" },
  { label: "Akan", value: "ak" },
  { label: "Albanian", value: "sq" },
  { label: "Amharic", value: "am" },
  { label: "Arabic", value: "ar" },
  { label: "Aragonese", value: "an" },
  { label: "Armenian", value: "hy" },
  { label: "Assamese", value: "as" },
  { label: "Avaric", value: "av" },
  { label: "Avestan", value: "ae" },
  { label: "Aymara", value: "ay" },
  { label: "Azerbaijani", value: "az" },
  { label: "Bambara", value: "bm" },
  { label: "Bashkir", value: "ba" },
  { label: "Basque", value: "eu" },
  { label: "Belarusian", value: "be" },
  { label: "Bengali", value: "bn" },
  { label: "Bislama", value: "bi" },
  { label: "Bosnian", value: "bs" },
  { label: "Breton", value: "br" },
  { label: "Bulgarian", value: "bg" },
  { label: "Burmese", value: "my" },
  { label: "Catalan, Valencian", value: "ca" },
  { label: "Central Khmer", value: "km" },
  { label: "Chamorro", value: "ch" },
  { label: "Chechen", value: "ce" },
  { label: "Chichewa, Chewa, Nyanja", value: "ny" },
  { label: "Chinese", value: "zh" },
  { label: "Church Slavonic, Old Slavonic, Old Church Slavonic", value: "cu" },
  { label: "Chuvash", value: "cv" },
  { label: "Cornish", value: "kw" },
  { label: "Corsican", value: "co" },
  { label: "Cree", value: "cr" },
  { label: "Croatian", value: "hr" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da" },
  { label: "Divehi, Dhivehi, Maldivian", value: "dv" },
  { label: "Dutch, Flemish", value: "nl" },
  { label: "Dzongkha", value: "dz" },
  { label: "English", value: "en" },
  { label: "Esperanto", value: "eo" },
  { label: "Estonian", value: "et" },
  { label: "Ewe", value: "ee" },
  { label: "Faroese", value: "fo" },
  { label: "Fijian", value: "fj" },
  { label: "Finnish", value: "fi" },
  { label: "French", value: "fr" },
  { label: "Fulah", value: "ff" },
  { label: "Gaelic, Scottish Gaelic", value: "gd" },
  { label: "Galician", value: "gl" },
  { label: "Ganda", value: "lg" },
  { label: "Georgian", value: "ka" },
  { label: "German", value: "de" },
  { label: "Greek, Modern (1453–)", value: "el" },
  { label: "Guarani", value: "gn" },
  { label: "Gujarati", value: "gu" },
  { label: "Haitian, Haitian Creole", value: "ht" },
  { label: "Hausa", value: "ha" },
  { label: "Hebrew", value: "he" },
  { label: "Herero", value: "hz" },
  { label: "Hindi", value: "hi" },
  { label: "Hiri Motu", value: "ho" },
  { label: "Hungarian", value: "hu" },
  { label: "Icelandic", value: "is" },
  { label: "Ido", value: "io" },
  { label: "Igbo", value: "ig" },
  { label: "Indonesian", value: "id" },
  { label: "Interlingua (International Auxiliary Language Association)", value: "ia" },
  { label: "Interlingue, Occidental", value: "ie" },
  { label: "Inuktitut", value: "iu" },
  { label: "Inupiaq", value: "ik" },
  { label: "Irish", value: "ga" },
  { label: "Italian", value: "it" },
  { label: "Japanese", value: "ja" },
  { label: "Javanese", value: "jv" },
  { label: "Kalaallisut, Greenlandic", value: "kl" },
  { label: "Kannada", value: "kn" },
  { label: "Kanuri", value: "kr" },
  { label: "Kashmiri", value: "ks" },
  { label: "Kazakh", value: "kk" },
  { label: "Kikuyu, Gikuyu", value: "ki" },
  { label: "Kinyarwanda", value: "rw" },
  { label: "Kirghiz, Kyrgyz", value: "ky" },
  { label: "Komi", value: "kv" },
  { label: "Kongo", value: "kg" },
  { label: "Korean", value: "ko" },
  { label: "Kuanyama, Kwanyama", value: "kj" },
  { label: "Kurdish", value: "ku" },
  { label: "Lao", value: "lo" },
  { label: "Latin", value: "la" },
  { label: "Latvian", value: "lv" },
  { label: "Limburgan, Limburger, Limburgish", value: "li" },
  { label: "Lingala", value: "ln" },
  { label: "Lithuanian", value: "lt" },
  { label: "Luba-Katanga", value: "lu" },
  { label: "Luxembourgish, Letzeburgesch", value: "lb" },
  { label: "Macedonian", value: "mk" },
  { label: "Malagasy", value: "mg" },
  { label: "Malay", value: "ms" },
  { label: "Malayalam", value: "ml" },
  { label: "Maltese", value: "mt" },
  { label: "Manx", value: "gv" },
  { label: "Maori", value: "mi" },
  { label: "Marathi", value: "mr" },
  { label: "Marshallese", value: "mh" },
  { label: "Mongolian", value: "mn" },
  { label: "Nauru", value: "na" },
  { label: "Navajo, Navaho", value: "nv" },
  { label: "Ndonga", value: "ng" },
  { label: "Nepali", value: "ne" },
  { label: "North Ndebele", value: "nd" },
  { label: "Northern Sami", value: "se" },
  { label: "Norwegian", value: "no" },
  { label: "Norwegian Bokmål", value: "nb" },
  { label: "Norwegian Nynorsk", value: "nn" },
  { label: "Occitan", value: "oc" },
  { label: "Ojibwa", value: "oj" },
  { label: "Oriya", value: "or" },
  { label: "Oromo", value: "om" },
  { label: "Ossetian, Ossetic", value: "os" },
  { label: "Pali", value: "pi" },
  { label: "Pashto, Pushto", value: "ps" },
  { label: "Persian", value: "fa" },
  { label: "Polish", value: "pl" },
  { label: "Portuguese", value: "pt" },
  { label: "Punjabi, Panjabi", value: "pa" },
  { label: "Quechua", value: "qu" },
  { label: "Romanian, Moldavian, Moldovan", value: "ro" },
  { label: "Romansh", value: "rm" },
  { label: "Rundi", value: "rn" },
  { label: "Russian", value: "ru" },
  { label: "Samoan", value: "sm" },
  { label: "Sango", value: "sg" },
  { label: "Sanskrit", value: "sa" },
  { label: "Sardinian", value: "sc" },
  { label: "Serbian", value: "sr" },
  { label: "Shona", value: "sn" },
  { label: "Sichuan Yi, Nuosu", value: "ii" },
  { label: "Sindhi", value: "sd" },
  { label: "Sinhala, Sinhalese", value: "si" },
  { label: "Slovak", value: "sk" },
  { label: "Slovenian", value: "sl" },
  { label: "Somali", value: "so" },
  { label: "South Ndebele", value: "nr" },
  { label: "Southern Sotho", value: "st" },
  { label: "Spanish, Castilian", value: "es" },
  { label: "Sundanese", value: "su" },
  { label: "Swahili", value: "sw" },
  { label: "Swati", value: "ss" },
  { label: "Swedish", value: "sv" },
  { label: "Tagalog", value: "tl" },
  { label: "Tahitian", value: "ty" },
  { label: "Tajik", value: "tg" },
  { label: "Tamil", value: "ta" },
  { label: "Tatar", value: "tt" },
  { label: "Telugu", value: "te" },
  { label: "Thai", value: "th" },
  { label: "Tibetan", value: "bo" },
  { label: "Tigrinya", value: "ti" },
  { label: "Tonga (Tonga Islands)", value: "to" },
  { label: "Tsonga", value: "ts" },
  { label: "Tswana", value: "tn" },
  { label: "Turkish", value: "tr" },
  { label: "Turkmen", value: "tk" },
  { label: "Twi", value: "tw" },
  { label: "Uighur, Uyghur", value: "ug" },
  { label: "Ukrainian", value: "uk" },
  { label: "Urdu", value: "ur" },
  { label: "Uzbek", value: "uz" },
  { label: "Venda", value: "ve" },
  { label: "Vietnamese", value: "vi" },
  { label: "Volapük", value: "vo" },
  { label: "Walloon", value: "wa" },
  { label: "Welsh", value: "cy" },
  { label: "Western Frisian", value: "fy" },
  { label: "Wolof", value: "wo" },
  { label: "Xhosa", value: "xh" },
  { label: "Yiddish", value: "yi" },
  { label: "Yoruba", value: "yo" },
  { label: "Zhuang, Chuang", value: "za" },
  { label: "Zulu", value: "zu" },
];


export const paypaySupportedCurrency = [
  { label: 'Australian dollar ($)', value: 'aud' },
  { label: 'Brazilian real (R$)', value: 'brl' },
  { label: 'Canadian dollar ($)', value: 'cad' },
  { label: 'Chinese renminbi yuan (¥)', value: 'cny' },
  { label: 'Czech koruna (Kč)', value: 'czk' },
  { label: 'Danish krone (kr)', value: 'dkk' },
  { label: 'Euro (€)', value: 'eur' },
  { label: 'Hong Kong dollar ($)', value: 'hkd' },
  { label: 'Hungarian forint (Ft)', value: 'huf' },
  { label: 'Israeli new sheqel (₪)', value: 'ils' },
  { label: 'Japanese yen (¥)', value: 'jpy' },
  { label: 'Malaysian ringgit (RM)', value: 'myr' },
  { label: 'Mexican peso ($)', value: 'mxn' },
  { label: 'New Taiwan dollar (NT$)', value: 'twd' },
  { label: 'New Zealand dollar ($)', value: 'nzd' },
  { label: 'Norwegian krone (kr)', value: 'nok' },
  { label: 'Philippine peso (₱)', value: 'php' },
  { label: 'Polish złoty (zł)', value: 'pln' },
  { label: 'British pound (£)', value: 'gbp' },
  { label: 'Russian ruble (₽)', value: 'rub' },
  { label: 'Singapore dollar ($)', value: 'sgd' },
  { label: 'Swedish krona (kr)', value: 'sek' },
  { label: 'Swiss franc (CHF)', value: 'chf' },
  { label: 'Thai baht (฿)', value: 'thb' },
  { label: 'United States dollar ($)', value: 'usd' },

]

export const widgetCurrency = { afn: '؋', all: 'L', dzd: 'دج', aoa: 'Kz', ars: '$', amd: '֏', awg: 'ƒ', aud: '$', azn: '₼', bsd: '$', bdt: '৳', bbd: 'Bds$', bzd: 'BZ$', bmd: '$', bob: 'Bs.', bam: 'KM', bwp: 'P', brl: 'R$', gbp: '£', bnd: '$', bgn: 'лв', bif: 'FBu', khr: '៛', cad: '$', cve: 'Esc', kyd: '$', xaf: 'FCFA', xpf: '₣', clp: '$', cny: '¥', cop: '$', kmf: 'CF', cdf: 'FC', crc: '₡', hrk: 'kn', czk: 'Kč', dkk: 'kr', djf: 'Fdj', dop: 'RD$', xcd: '$', egp: '£', etb: 'Br', eur: '€', fkp: '£', fjd: '$', gmd: 'D', gel: '₾', gip: '£', gtq: 'Q', gnf: 'FG', gyd: '$', htg: 'G', hnl: 'L', hkd: '$', huf: 'Ft', isk: 'kr', inr: '₹', idr: 'Rp', ils: '₪', jmd: 'J$', jpy: '¥', kzt: '₸', kes: 'KSh', kgs: 'som', lak: '₭', lbp: '£', lsl: 'L', lrd: '$', mop: 'MOP$', mkd: 'ден', mga: 'Ar', mwk: 'MK', myr: 'RM', mvr: 'ރ', mro: 'UM', mur: 'Rs', mxn: '$', mdl: 'L', mnt: '₮', mad: 'د.م.', mzn: 'MT', mmk: 'K', nad: '$', npr: 'रू', ang: 'ƒ', twd: 'NT$', nzd: '$', nio: 'C$', ngn: '₦', nok: 'kr', pkr: '₨', pab: 'B/.', pgk: 'K', pyg: '₲', pen: 'S/.', php: '₱', pln: 'zł', qar: 'ر.ق', ron: 'L', rub: '₽', rwf: 'RWF', std: 'Db', shp: '£', svc: '₡', wst: 'WST', sar: 'ر.س', rsd: 'дин.', scr: 'Rs', sll: 'SLL', sgd: '$', sbd: '$', sos: 'SOS', zar: 'R', krw: '₩', lkr: 'රු', srd: 'SRD', szl: 'E', sek: 'kr', chf: 'CHF', tjs: 'ЅМ', tzs: 'TSh', thb: '฿', top: 'T$', ttd: 'TT$', try: '₺', ugx: 'UGX', uah: '₴', aed: 'د.إ', usd: '$', uyu: '$U', uzs: 'soʻm', vuv: 'VT', vnd: '₫', xof: 'CFA', yer: '﷼', zmw: 'ZMW' };


export const emailContentObject = {
  newBooking: {
    'booking_date': 'Date of (seat/table) booking or room checkIn and checkOut date',
    'booking_time': 'Time of Booking',
    'booking_type': 'Type of Booking(seat , table , room)',
    'company_address': 'Address of company',
    'business_name': 'Name of your business',
    'company_phoneno': 'Phone number of company',
    'client_name': 'Name of client',
    'client_email': 'Email of client',
    'payment_method': 'Payment Method( strip , paypal , cash)',
    'payment_status': 'Payment status',
    'transaction_id': 'Transaction Id',
    'total_price': 'Total price of event booking ',
    'selected_types_table': 'Table of all the selected (room/seat/table) types with their name,price and quantity.'
  },
  appointmentDecline: {
    'appointment_date': 'Date of appointment',
    'appointment_time': 'Time of appointment',
    'cancellation_reason': 'Reason mentioned while cancelling appointment',
    'company_address': 'Address of company',
    'business_name': 'Name of your business',
    'company_phoneno': 'Phone number of company',
    'client_name': 'Name of client',
    'client_email': 'Email of client',
    'payment_type': 'Payment type',
    'staff_name': 'Name of staff',
    'total_price': 'Total price of appointment booking ',
  },
  newAppointment: {
    'appointment_date': 'Date of appointment',
    'appointment_time': 'Time of appointment',
    'company_address': 'Address of company',
    'business_name': 'Name of your business',
    'company_phoneno': 'Phone number of company',
    'client_name': 'Name of client',
    'client_email': 'Email of client',
    'payment_method': 'Payment Method( strip , paypal , cash)',
    'payment_status': 'Payment status',
    'staff_name': 'Name of staff',
    'transaction_id': 'Transaction Id',
    'total_price': 'Total price of appointment booking ',
  },
  newEventRegister: {
    'campaign_name': 'Name of campaign',
    'event_date_and_time': 'Date and time of event',
    'company_address': 'Address of company',
    'business_name': 'Name of your business',
    'company_phoneno': 'Phone number of company',
    'client_name': 'Name of client',
    'client_email': 'Email of client',
    'payment_method': 'Payment Method( strip , paypal , cash)',
    'payment_status': 'Payment status',
    'transaction_id': 'Transaction Id',
    'total_price': 'Total price of event booking ',
    'selected_types_table': 'Table of all the selected tickets with their name,price and quantity.'
  },

  visitorMailVerify: {
    'verification_code': 'Verification code',
    'client_email': 'Email of client'
  },

  // Admin 
  accountCreation: {
    'client_full_name': 'Full Name of client',
    'client_first_name': 'First Name of client',
    'client_last_name': 'Last Name of client',
    'client_email': 'Email of client',
    'client_password': 'Password of client account'
  },
  resetpassword: {
    'client_full_name': 'Full Name of client',
    'client_first_name': 'First Name of client',
    'client_last_name': 'Last Name of client',
    'client_email': 'Email of client',
    'reset_link_url': 'URL to reset password'
  },
  subsciptionSuspended: {
    'client_full_name': 'Full Name of client',
    'client_first_name': 'First Name of client',
    'client_last_name': 'Last Name of client',
    'subscriptionId': 'User plan subscription id',
    'subscriptionPlan': 'User subscribed plan name',
    'next_billing_time': 'Subscription renewal date',
    'paymentDate': 'Date when subscription payment initiated',
    'paymentMethod': 'Payment account (stripe/paypal)'
  },

  subsciptionRenewal: {
    'client_full_name': 'Full Name of client',
    'client_first_name': 'First Name of client',
    'client_last_name': 'Last Name of client',
    'subscriptionId': 'User plan subscription id',
    'subscriptionPlan': 'User subscribed plan name',
    'next_billing_time': 'Subscription renewal date',
    'subscription_start_date': 'Date when subscription is activated/started',
    'paymentDate': 'Date when subscription payment initiated',
    'paymentMethod': 'Payment account (stripe/paypal)',
    'amount_paid': 'Price of plan',
    'invoiceNumber': 'Invoice/transaction id of payment'
  },
}


export const words = {
  commonWords: {
    1: "Time Slot",
    3: "Venue",
    4: "Continue",
    5: "Verify",
    6: "Name",
    7: "Email",
    8: "Back",
    9: "Contact",
    10: "Bill To",
    11: "Pay",
    12: "Free",
    13: "Description",
    14: "Available",
    15: "Unavailable",
    16: "Total",
    17: "Total Amount",
    18: "and",
    19: "Selected",
    20: "Quantity",
    21: "Price",
    22: "Amount",
    23: "Date",
    24: "Cash",
    25: "Paypal",
    26: "Stripe",
    27: "Time",
    28: "Sold Out",
    30: "Submit",
    31: "Payment Method",
    32: "Transaction Id",
    33: "Select an option",
    34: "CASH ON COUNTER",
    35: "Enter OTP",
    36: "Resend OTP",
    37: "Resend OTP in {seconds}",
    38: "Please enter a value",
    39: "Please verify your email",
    40: "Please select a value",
    41: "Please select a date",
    42: "Please enter a valid email address.",
    43: "Please enter a valid phone number.",
    44: "Invalid OTP. Please enter a 6-digit OTP.",
    45: "Incorrect OTP entered.",
    86: "OTP has expired. Please try resend OTP."
  },

  appointmentWords: {
    46: "Selected Time",
    47: "Selected Staff",
    48: "Appointment Details",
    49: "Appointment Date",
    50: "Select A Staff Member",
    51: "Your {employeeService} appointment with {employee} is scheduled for {date} at {selectedTime}.",
    52: "Your appointment is scheduled for {selectedDate} at {selectedTime}.",
    53: "Please provide your details in the form below to proceed.",
    54: "Price for the service is {price}. How you would like to pay",
    55: "Oops! No slots available for chosen date, try to choose a different date. Thank you!",
    56: "No slots available for this day.",
    57: "You already have an appointment for this day.",
  },

  eventWords: {
    58: "Event Details",
    59: "Organised By",
    60: "Date and Time",
    61: "Select Tickets",
    62: "Free",
    63: "How you would like to pay:",
    64: "Select at least one ticket",
    65: "Registration has not started yet.",
    66: "Registration has been closed.",
    67: "You have selected {selectedTickets} ticket. Your total payable amount is {price}.",
    68: "Please provide your details in the form below to proceed with booking.",
    69: "Sorry, all tickets for this event have been booked. We're fully sold out! Please stay tuned for our future updates. Thank you for your interest!",
  },

  bookingWords: {
    70: "Check In",
    71: "Check Out",
    72: "Select",
    73: "Room",
    74: "Seat",
    75: "Table",
    77: "Person per Room",
    78: "No of Person - {personPerTable}",
    79: "Select at least one option",
    80: "How you would like to pay",
    81: "You have selected {selectedRooms} for {dateCheckIn} to {dateCheckout}. Your total cost is {price}.",
    82: "Please provide your details in the form below to proceed with booking.",
    83: "Oops!, currently no rooms available for chosen dates. Try to select different dates. Thank you for your interest!",
    84: "You have selected {selectedSeat-Table} for {selectedDate}, {selectedTime}. Your total cost is {price}.",
    85: "Sorry, currently no {reservationType} available for chosen date and time. Try selecting another date and time. Thank you for your interest!",
    87: "Check-out date should be greater than check-in date."
  }
} 

// .replace(/\{personPerTable\}/g, ele.personPerTable)